name: tokTales Release

on:
  release:
    types:
      - published

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: tokTales-master
      run: ./gradlew build
    - name: Deploy to Bintray
      env:
        BINTRAY_USER: ${{secrets.BINTRAY_USER}}
        BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
      working-directory: tokTales-master
      run: ./gradlew bintrayUpload -Pbintray.version -Pbintray.user=$BINTRAY_USER -Pbintray.key=$BINTRAY_KEY
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{secrets.PRIVATE_PACKAGES_TOKEN}}
      working-directory: tokTales-master
      run: ./gradlew publish
