name: tokTales Publish

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: tokTales-master
      run: ./gradlew build
    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
        prefix: tokTales-master-0.1.0
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{secrets.PRIVATE_PACKAGES_TOKEN}}
      working-directory: tokTales-master
      run: ./gradlew publish -PbuildNumber=$BUILD_NUMBER
    - name: Generate Javadoc
      working-directory: tokTales-master
      run: ./gradlew javadocAggregated
    - name: Get project version from Gradle
      working-directory: tokTales-master
      run: echo ::set-env name=PROJECT_VERSION::$(./gradlew properties --console=plain -q | grep "^version:" | awk '{printf $2}')
    - name: Publish nightly Javadoc
      uses: seanmiddleditch/gha-publish-to-git@78b4078ce1f8925a4d99e4e18e14a37d98f27b64
      with:
        repository: Tokelon/tokTales-docs
        branch: master
        github_pat: ${{secrets.GITHUB_PAT}}
        source_folder: tokTales-master/build/docs/javadoc
        target_folder: api-docs/nightly/javadoc
        commit_message: Update nightly api-docs with version ${{env.PROJECT_VERSION}}-${{env.BUILD_NUMBER}}
