name: tokTales Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: tokTales-master
      run: ./gradlew build
    - name: Generate build number
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
        prefix: tokTales-master-0.1.0
    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{secrets.PRIVATE_PACKAGES_TOKEN}}
      working-directory: tokTales-master
      run: ./gradlew publish -PbuildNumber=$BUILD_NUMBER
    - name: Generate Javadoc
      working-directory: tokTales-master
      run: ./gradlew javadocAggregated
    - name: Publish Javadoc
      uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: Tokelon/tokTales-docs
        branch: master
        github_pat: ${{secrets.GITHUB_PAT}}
        source_folder: tokTales-master/build/docs/javadoc
        target_folder: api-docs/nightly/javadoc
        commit_message: Update nightly api-docs from build ${{env.BUILD_NUMBER}}
